# Generated by Django 5.1.4 on 2025-02-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('pnum', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('passw', models.CharField(max_length=12)),
            ],
        ),
    ]
