apiVersion: v1
kind: Service
metadata:
  name: train-service
spec:
  type: NodePort
  selector:
    app: train-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30777
